### ISSUE TITLE
Formatting is *important*!

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/sort-it-out#4]
Hey 👲!

CS (code style), code formatting, etc etc are various names for same thing: "**Formatting is important.**";

PHP has a _PSR-2_ standard that dictates how to format your code. Although you do not need to follow these rules, it's considered a good practice to follow. It makes code formatting consistent across all developers working on a particular project, it is easier to read, etc etc

You code has multiple issues:

1. "There must always be a space after opening tag (`<?php`)."
2. "Every file must end with an empty line." (*SC*: `"ensure_newline_at_eof_on_save": true`)
3. "Intendation level must be *4 spaces*, not tabs." (*SC*: `"tab_size": 4, "translate_tabs_to_spaces": true`)
4. If statement written as follows: `if (...) {`
5. No `;` after `if, for, switch, do, while`

There might be more things to consider, so please fix those above, and we will take a look at the rest then 🌵

**Comment by kristiankostecky** [comment]
Resolved 3458f9d
