### ISSUE TITLE
For every single one

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/sort-it-out#5]
When you want to iterate over every element in an array, there are two ways to do such thing in PHP.

*first*
```php
$names = ['john', 'james', 'oliver'];

for ($i = 1; $i < count($names); $i++) {
    if ($names[$i] == 'james') {
        echo "I have found JAMES!!";
    }
}
```

*second*
```php
$names = ['john', 'james', 'oliver'];

foreach ($names as $name) {
    if ($name == 'james') {
        echo "I have found JAMES!!";
    }
}
```

Second option is considered a better option, because:
- it reads better
- takes less time and code to write
- `foreach ($names as $name)` explains better what you are trying to do than `for ($i = 1; $i < count($names); $i++) { $names[i]... }`

Keep up the good work 🌵

**Comment by kristiankostecky** [comment]
Resolved in 8a0176d
