### ISSUE TITLE
Printing can be an issue sometimes

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/sort-it-out#6]
Printing text on the screen can get messy sometimes.

```php
echo "boys: " .implode(", ",$boys). "\ngirls: " .implode(", ",$girls);
```

This is an example of that. It is hard to read and I hardly now how it's going to look when it's printed. For such "text formatting" tasks, there is a solution called `printf()`.

```php
printf("boys %s\ngirls %s", implode(", ", $boys), implode(", ", $girls));
```

You first specify a pattern and then the vales that should be placed in the _pattern string_.

_%s_ represents string (similar to c language)

**Comment by kristiankostecky** [comment]
Resolved in f3b0357
