### ISSUE TITLE
Hide the logic, hide the trouble

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/sort-it-out#7]
There is a convention in programming called **DRY** (**D**o not **R**epeat **Y**ouself). It says that you should not write the same piece of logic more than once. What you should do instead, is that you should **hide** the logic behind a _class_/_function_ etc..

Look at this piece of code:
```php
foreach ($data as $person) {
    if ($person['gender'] == 'male') {
        $boys[] = $person['name'];
    }
    if ($person['gender'] == 'female') {
        $girls[] = $person['name'];
    }
}
```

The *if* statement is repeated in there.

```php
if ($person['gender'] == $gender) {
    $names[] = $person['name'];
}
```

You might extract the logic by creating a function such as:

```php
function listNames($gender, $people) {
    $names = [];

    foreach($people as $person) {
        if ($person['gender']  == $gender) {
            $names[] = $person['name'];
        }
    }

    return implode(', ', $names);
}
```

It does basically the same thing and might seem a little more complex. **BUT** look at how would we implement printing the results while using `listNames()` function. It would probably look like this:

```php
printf(
    "boys: %s\ngirls: %n",
    listNames('female', $data),
    listNames('male', $data)
);
```

Pretty easy, isn't it? This is the important thing to remember. When looking at this `printf(...);`, you do not actually need to know how `listNames()` function works. You do not really have to care, because, you just know it will return a list of names for given gender.

This _thingy_ might seem a little overwhelming at beginning, but once learnt the basics, it will be much easier to maintain. 🌵

**Comment by kristiankostecky** [comment]
Resolved in 7f88694 💡
